server:
  port: ":8082"
  mode: "debug"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "ecommerce"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

logging:
  level: "info"
  format: "json"